// Auto-generated from questions.md by convert.js
// Do not edit this file directly. Edit questions.md instead.

const techniques = [
    {
        "name": "摩擦法",
        "desc": "以掌、指或肘貼附於體表，作直線往返或環形移動的操作。",
        "details": {
            "definition": [
                "操作者以手部手指、手掌、大魚際、小魚際等部位",
                "貼於操作部位，進行<strong>環旋滑動</strong>",
                "<strong>直線往返滑動</strong>的手法"
            ],
            "essentials": [
                "執行<strong>摩法</strong>手法操作時，向下壓的力量要<strong>小於環旋滑動的力量</strong>",
                "執行<strong>擦法</strong>手法操作時，向下壓的力量要<strong>小於直線往返滑動的力量</strong>",
                "使皮膚產生溫熱感"
            ],
            "areas": [
                "全身各體表部位"
            ],
            "effects": [
                "體表紓緩放鬆"
            ]
        },
        "image": ""
    },
    {
        "name": "滾法",
        "desc": "以手背近小指側處附著於治療部位，透過腕關節的屈伸運動和前臂的旋轉運動，使手背在治療部位上作連續不斷的來回滾動。",
        "details": {
            "definition": [
                "操作者以<strong>手掌背側與小魚際為附著點</strong>",
                "結合<strong>腕關節屈伸</strong>及<strong>前臂旋轉運動</strong>，貼於操作部位",
                "做<strong>連續往返滾動</strong>的手法"
            ],
            "essentials": [
                "執行滾法手法操作時，應<strong>放鬆肩臂、沉肩、垂肘、鬆腕、五指微屈</strong>",
                "向下壓的力量要<strong>小於滾動的力量</strong>",
                "出手方向與胸前約呈 <strong>45° 角</strong>"
            ],
            "areas": [
                "全身各體表部位"
            ],
            "effects": [
                "體表紓緩放鬆"
            ]
        },
        "image": ""
    },
    {
        "name": "拍擊法",
        "desc": "用手掌、拳背、手指或桑枝棒等，有節奏地拍打體表。",
        "details": {
            "definition": [
                "操作者<strong>掌指關節微屈</strong>",
                "利用<strong>腕部擺動帶動虛掌</strong>",
                "著力於操作部位的手法"
            ],
            "essentials": [
                "執行拍擊法手法操作時，<strong>手虛掌</strong>",
                "拍打應<strong>迅速平穩而有節奏</strong>",
                "力量應<strong>由輕到重</strong>"
            ],
            "areas": [
                "全身各體表部位"
            ],
            "effects": [
                "常用於<strong>調理結束前之整體紓緩放鬆</strong>"
            ]
        },
        "image": ""
    },
    {
        "name": "推法",
        "desc": "用指、掌、拳、肘等部位，著力於體表一定部位或穴位上，進行單方向的直線移動。",
        "details": {
            "definition": [
                "操作者以<strong>手指、手掌、掌根、手肘等部位</strong>",
                "著力於操作部位",
                "<strong>單向直線推動</strong>的手法"
            ],
            "essentials": [
                "執行推法手法操作時，動作<strong>力量要穩</strong>",
                "<strong>速度和緩均勻</strong>"
            ],
            "areas": [
                "全身各<strong>肌肉豐厚部位</strong>"
            ],
            "effects": [
                "<strong>深層肌肉紓緩放鬆</strong>"
            ]
        },
        "image": ""
    },
    {
        "name": "拿法",
        "desc": "用大拇指與其他手指相對用力，提捏或揉捏肌膚與肌肉。",
        "details": {
            "definition": [
                "操作者<strong>拇指與其餘四指相對用力</strong>",
                "<strong>捏而提起操作部位</strong>",
                "進行<strong>一鬆一緊捏提</strong>的手法"
            ],
            "essentials": [
                "執行拿法手法操作時，<strong>手指力量應對稱</strong>",
                "與肌肉作用產生<strong>一鬆一緊捏提的效果</strong>",
                "動作<strong>和緩而有連貫性</strong>"
            ],
            "areas": [
                "全身各<strong>肌肉豐厚部位</strong>"
            ],
            "effects": [
                "<strong>深層肌肉紓緩放鬆</strong>"
            ]
        },
        "image": ""
    },
    {
        "name": "按法",
        "desc": "用手指、手掌、肘部等部位，著力於體表特定部位或穴位，逐漸用力下壓。",
        "details": {
            "definition": [
                "操作者以<strong>手指、手掌、掌根、手肘等部位按於操作部位</strong>",
                "<strong>垂直逐漸用力</strong>",
                "<strong>向下按壓</strong>的手法"
            ],
            "essentials": [
                "執行按法手法操作時，<strong>用力要穩、要垂直</strong>",
                "<strong>由輕漸重，按而留之</strong>",
                "<strong>不可移動，切忌暴力</strong>"
            ],
            "areas": [
                "全身各<strong>肌肉豐厚部位</strong>"
            ],
            "effects": [
                "<strong>深層肌肉紓緩放鬆</strong>"
            ]
        },
        "image": ""
    },
    {
        "name": "揉法",
        "desc": "用手掌大魚際、掌根或手指指腹定點於治療部位，作輕柔緩和的環形移動，帶動皮下組織。",
        "details": {
            "definition": [
                "操作者以<strong>手指、手掌、掌根、手肘等部位</strong>",
                "著力於操作部位",
                "進行<strong>環形揉動，帶動深層肌肉</strong>的手法"
            ],
            "essentials": [
                "執行揉法手法操作時，<strong>揉動動作需柔和</strong>",
                "達到<strong>帶動深層肌肉之效果</strong>",
                "<strong>與按法合併操作</strong>"
            ],
            "areas": [
                "全身各<strong>肌肉豐厚部位</strong>"
            ],
            "effects": [
                "<strong>深層肌肉紓緩放鬆</strong>"
            ]
        },
        "image": ""
    },
    {
        "name": "撥法",
        "desc": "用指端深按於治療部位的肌束、肌腱或韌帶上，像彈撥琴弦一樣地作橫向撥動。",
        "details": {
            "definition": [
                "操作者以<strong>手指、掌根或手肘部等部位</strong>",
                "著力於操作部位",
                "與<strong>條索狀之肌肉或肌腱、韌帶呈直角方向撥動</strong>的手法"
            ],
            "essentials": [
                "執行撥法手法操作時，<strong>不與皮膚產生摩擦</strong>",
                "<strong>均勻和緩，幅度不可過大</strong>",
                "<strong>與按法合併操作</strong>"
            ],
            "areas": [
                "全身各<strong>肌肉豐厚部位</strong>"
            ],
            "effects": [
                "<strong>深層肌肉紓緩放鬆</strong>"
            ]
        },
        "image": ""
    },
    {
        "name": "抖法",
        "desc": "握住患者肢體遠端，用力做連續、小幅度的上下顫動。",
        "details": {
            "definition": [
                "操作者<strong>雙手握住上肢或下肢的遠端</strong>",
                "在<strong>牽拉狀態下做抖動</strong>的手法"
            ],
            "essentials": [
                "執行抖法手法操作時，<strong>振動幅度要小</strong>",
                "<strong>頻率要快</strong>",
                "<strong>要有連續性</strong>"
            ],
            "areas": [
                "<strong>四肢關節部位</strong>"
            ],
            "effects": [
                "<strong>關節紓緩放鬆</strong>"
            ]
        },
        "image": ""
    },
    {
        "name": "搖法",
        "desc": "使關節作被動性的環轉運動。",
        "details": {
            "definition": [
                "操作者<strong>運用雙手</strong>",
                "對<strong>四肢關節部位</strong>(如肩、肘、腕、髖、膝、踝等)",
                "做<strong>旋轉活動</strong>的手法"
            ],
            "essentials": [
                "執行搖法手法操作時，<strong>搖動幅度要由小到大</strong>",
                "<strong>速度要由慢到快</strong>",
                "<strong>動作和緩，切忌暴力</strong>"
            ],
            "areas": [
                "<strong>四肢關節部位</strong>"
            ],
            "effects": [
                "<strong>關節紓緩放鬆</strong>"
            ]
        },
        "image": ""
    }
];
